#!/usr/bin/env bash

set -e
set -u

CONTEXT=${1:-"dev"}

export FLASK_APP=rollinghub
if [[ $CONTEXT == "dev" ]] ; then
    source venv/Scripts/activate
    export FLASK_ENV=development
    export DATABASE_URL=postgresql://localhost:5432/rollinghub
    flask init-db
    flask run
fi
if [[ $CONTEXT == "stage" ]] ; then
    source venv/Scripts/activate
    export DATABASE_URL=postgresql://localhost:5432/rollinghub
    export PORT=5000
    flask init-db
    waitress-serve --port="$PORT" --call 'rollinghub:create_app'
fi
if [[ $CONTEXT == "init" ]] ; then
    export FLASK_APP=rollinghub
    flask init-db
fi
if [[ $CONTEXT == "prod" ]] ; then
    gunicorn --bind 0.0.0.0:$PORT rollinghub:create_app
fi