#!/usr/bin/env bash

set -e
set -u

CONTEXT=${1:-"dev"}

export FLASK_APP=rollinghub
if [[ $CONTEXT == "dev" ]] ; then
    source venv/Scripts/activate
    export FLASK_ENV=development
    export DATABASE_URL=postgresql://localhost:5432/rollinghub
    flask init-db
    flask run
fi
if [[ $CONTEXT == "stage" ]] ; then
    source venv/Scripts/activate
    export DATABASE_URL=postgresql://localhost:5432/rollinghub
    flask init-db
    python ./rollinghub/wsgi.py
fi
if [[ $CONTEXT == "prod" ]] ; then
    python ./rollinghub/wsgi.py
fi